- name: PKGS Everyone
  hosts: all
  become: true
  roles:
  - setting
  - updating
  - autoupgrade

- name: PKGS PDostal
  hosts: pdostal
  become: true
  roles:
  - sources
  - keychain
  - Instaling

