- set_fact:
    subdistro: debian
  when: ansible_architecture == 'x86_64'
- set_fact:
    subdistro: raspbian
  when: ansible_architecture == 'armv6l' or ansible_architecture == 'armv7l'

- name: Set locales properly
  when: ansible_distribution == 'Debian'
  template: src=environment dest=/etc/environment

- name: Install HTTPS module
  when: ansible_distribution == 'Debian'
  apt: name=apt-transport-https state=latest

- name: Paste sources.list
  when: ansible_distribution == 'Debian'
  template: src={{ subdistro }}.list dest=/etc/apt/sources.list

- name: Add GPG for flighradar24
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgp.mit.edu id=40C430F5
- name: Add GPG for adafruit
  when: ansible_distribution == 'Debian'
  apt_key: state=present url=https://apt.adafruit.com/apt.adafruit.com.gpg.key
- name: Add GPG for passenger
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgpkeys.mit.edu id=561F9B9CAC40B2F7
- name: Add GPG for openvpn
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgpkeys.mit.edu id=8E6DA8B4E158C569
- name: Add GPG for knot
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgpkeys.mit.edu id=AC0E47584A7A714D
- name: Add GPG for nginx
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgpkeys.mit.edu id=ABF5BD827BD9BF62
- name: Add GPG for new relic
  when: ansible_distribution == 'Debian'
  apt_key: state=present keyserver=pgpkeys.mit.edu id=548C16BF
