- name: Update repositories
  when: ansible_os_family == 'Debian'
  apt: update_cache=yes
- name: Update repositories
  when: ansible_os_family == 'FreeBSD'
  shell: pkg update

- name: Upgrade all packages
  when: ansible_os_family == 'Debian'
  apt: upgrade=dist force=yes
- name: Upgrade all packages
  when: ansible_os_family == 'FreeBSD'
  shell: pkg upgrade -y
