- name: Update repositories [Debian]
  when: ansible_os_family == 'Debian'
  apt: update_cache=yes
- name: Update repositories [RedHat]
  when: ansible_os_family == 'RedHat'
  shell: yum update -y
- name: Update repositories [FreeBSD]
  when: ansible_os_family == 'FreeBSD'
  shell: pkg update

- name: Upgrade all packages [Debian]
  when: ansible_os_family == 'Debian'
  apt: upgrade=dist
- name: Upgrade all packages [RedHat]
  when: ansible_os_family == 'RedHat'
  yum: name=* state=latest
- name: Upgrade all packages [FreeBSD]
  when: ansible_os_family == 'FreeBSD'
  shell: pkg upgrade -y
